FROM archlinux@sha256:ceac417c19645d21630c120fa123942aa1fc5988faab14e67222013cb11f31bb

RUN pacman -Syu --noconfirm \
    git \
    python \
    python-pip \
    python-build \
    python-installer \
    python-hatchling \
    namcap \
    shellcheck
